# Generated by Django 6.0.1 on 2026-01-13 20:14

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('is_service_provider', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('FURNITURE', 'Furniture'), ('ELECTRONICS', 'Electronics'), ('VEHICLES', 'Vehicles'), ('REAL_ESTATE', 'Real Estate'), ('HOME_APPLIANCES', 'Home Appliances'), ('CLOTHING', 'Clothing & Accessories'), ('BOOKS', 'Books & Media'), ('SPORTS', 'Sports Equipment'), ('OTHER', 'Other')], max_length=50)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('LIKE_NEW', 'Like New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='static/products/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='static/products/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='static/products/')),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('contact_whatsapp', models.CharField(blank=True, max_length=15)),
                ('contact_email', models.BooleanField(default=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('contact_info', models.CharField(blank=True, help_text='e.g., WhatsApp: 1234567890, Call me at...', max_length=255)),
                ('is_visible', models.BooleanField(default=True, help_text='Seller can hide inappropriate comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='local_user.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='static/profiles/')),
                ('role', models.CharField(choices=[('USER', 'User'), ('SERVICE', 'Service Provider')], default='USER', max_length=10)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('pricing_type', models.CharField(blank=True, choices=[('FIXED', 'Fixed Price'), ('FLEXIBLE', 'Flexible')], max_length=20)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text='Average base/visiting charge', max_digits=10, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_reviews', models.IntegerField(default=0)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('availability', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('service_locations', models.JSONField(blank=True, default=list)),
                ('is_marketplace_seller', models.BooleanField(default=False)),
                ('marketplace_rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('marketplace_reviews', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.TextField()),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('scheduled_date', models.DateTimeField()),
                ('quote_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price quoted by provider', max_digits=10, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, help_text='Final price paid by user', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUOTE_GIVEN', 'Quote Given'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('provider_notes', models.TextField(blank=True)),
                ('user_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quoted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_made', to=settings.AUTH_USER_MODEL)),
                ('service_provider', models.ForeignKey(limit_choices_to={'role': 'SERVICE'}, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_received', to='local_user.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('FRAUD', 'Fraud/Scam'), ('BAD_SERVICE', 'Poor Service Quality'), ('UNPROFESSIONAL', 'Unprofessional Behavior'), ('HARASSMENT', 'Harassment'), ('SAFETY', 'Safety Concern'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='static/reports/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, help_text='Related booking if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='local_user.booking')),
                ('reported_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_as_provider', to='local_user.profile')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='local_user.booking')),
                ('provider', models.ForeignKey(limit_choices_to={'role': 'SERVICE'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='local_user.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
