# Generated by Django 6.0.1 on 2026-01-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='availability',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
