# Generated by Django 6.0.1 on 2026-02-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price_distribution_note',
            field=models.TextField(blank=True),
        ),
    ]
