# Generated by Django 6.0.1 on 2026-01-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_user', '0002_profile_availability_profile_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='service_locations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
