# Generated by Django 6.0.1 on 2026-09-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_user', '0002_productcommentreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pricing_type',
            field=models.CharField(blank=True, choices=[('FIXED', 'Fixed Price'), ('HOURLY', 'Hourly Rate'), ('FLEXIBLE', 'Flexible')], max_length=20),
        ),
    ]
