# Generated by Django 6.0.1 on 2026-01-12 20:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_user', '0003_profile_service_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='duration_hours',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hourly_rate',
        ),
        migrations.AddField(
            model_name='booking',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final price paid by user', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='quote_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price quoted by provider', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='quoted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_marketplace_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='marketplace_rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='marketplace_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('QUOTE_GIVEN', 'Quote Given'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average base/visiting charge', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pricing_type',
            field=models.CharField(blank=True, choices=[('FIXED', 'Fixed Price'), ('FLEXIBLE', 'Flexible')], max_length=20),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('FURNITURE', 'Furniture'), ('ELECTRONICS', 'Electronics'), ('VEHICLES', 'Vehicles'), ('REAL_ESTATE', 'Real Estate'), ('HOME_APPLIANCES', 'Home Appliances'), ('CLOTHING', 'Clothing & Accessories'), ('BOOKS', 'Books & Media'), ('SPORTS', 'Sports Equipment'), ('OTHER', 'Other')], max_length=50)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('LIKE_NEW', 'Like New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='static/products/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='static/products/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='static/products/')),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('contact_whatsapp', models.CharField(blank=True, max_length=15)),
                ('contact_email', models.BooleanField(default=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('contact_info', models.CharField(blank=True, help_text='e.g., WhatsApp: 1234567890, Call me at...', max_length=255)),
                ('is_visible', models.BooleanField(default=True, help_text='Seller can hide inappropriate comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='local_user.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('FRAUD', 'Fraud/Scam'), ('BAD_SERVICE', 'Poor Service Quality'), ('UNPROFESSIONAL', 'Unprofessional Behavior'), ('HARASSMENT', 'Harassment'), ('SAFETY', 'Safety Concern'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='static/reports/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, help_text='Related booking if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='local_user.booking')),
                ('reported_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_as_provider', to='local_user.profile')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
