# Generated by Django 6.0.1 on 2026-09-07 22:57

from django.db import migrations, models


def normalize_existing_locations(apps, schema_editor):
    Profile = apps.get_model('local_user', 'Profile')
    for profile in Profile.objects.all():
        updated = False
        if profile.location and profile.location.lower() in ('bhayender', 'bhayander'):
            profile.location = 'Bhayandar'
            updated = True
        if profile.service_locations and isinstance(profile.service_locations, list):
            new_svc_locs = []
            for s in profile.service_locations:
                if str(s).strip().lower() in ('bhayender', 'bhayander'):
                    new_svc_locs.append('Bhayandar')
                    updated = True
                else:
                    new_svc_locs.append(s)
            profile.service_locations = new_svc_locs
        if updated:
            profile.save()


def reverse_normalize(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('local_user', '0003_alter_profile_pricing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, choices=[('Churchgate', 'Churchgate'), ('Marine Lines', 'Marine Lines'), ('Charni Road', 'Charni Road'), ('Grant Road', 'Grant Road'), ('Mumbai Central', 'Mumbai Central'), ('Mahalaxmi', 'Mahalaxmi'), ('Lower Parel', 'Lower Parel'), ('Prabhadevi', 'Prabhadevi'), ('Dadar', 'Dadar'), ('Matunga Road', 'Matunga Road'), ('Mahim', 'Mahim'), ('Bandra', 'Bandra'), ('Khar Road', 'Khar Road'), ('Santacruz', 'Santacruz'), ('Vile Parle', 'Vile Parle'), ('Andheri', 'Andheri'), ('Jogeshwari', 'Jogeshwari'), ('Ram Mandir', 'Ram Mandir'), ('Goregaon', 'Goregaon'), ('Malad', 'Malad'), ('Kandivali', 'Kandivali'), ('Borivali', 'Borivali'), ('Dahisar', 'Dahisar'), ('Mira Road', 'Mira Road'), ('Bhayandar', 'Bhayandar'), ('Naigaon', 'Naigaon'), ('Vasai Road', 'Vasai Road'), ('Nalasopara', 'Nalasopara'), ('Virar', 'Virar')], max_length=50),
        ),
        migrations.RunPython(normalize_existing_locations, reverse_normalize),
    ]

